---
-
  connection: local
  hosts: localhost
  name: "Provision an EC2 Instance"
  vars_files:
        - conf/group_vars/conf.yml
  tasks:
    -
      local_action:
        description: "Security Group for webserver Servers"
        module: ec2_group
        name: "{{ security_group }}"
        region: "{{ region }}"
        rules:
          -
            cidr_ip: 0.0.0.0/0
            from_port: 80
            proto: tcp
            to_port: 85
          -
            cidr_ip: 0.0.0.0/0
            from_port: 22
            proto: tcp
            to_port: 22
        rules_egress:
          -
            cidr_ip: 0.0.0.0/0
            proto: all
      name: "Create a security group"
      register: my_security_group


#      allInOne started
    -
      local_action:
        count: "{{ count }}"
        group_id: "{{ my_security_group.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ imageID }}"
        wait: true
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        private_ip: 172.31.30.100
        module: ec2
      name: "Create a Instance (allInOne)"
      register: ec2
      when: allInOne == true

    - name: Add new webInstance to host group(allInOne)
      add_host: hostname={{ item.public_ip }} groupname=webInstance
      with_items: ec2.instances
      when: allInOne == true


    - name: Wait for SSH to come up in webInstance(allInOne)
      local_action: wait_for
                          host={{ item.public_ip }}
                          port=22
                          state=started
      with_items: ec2.instances
      when: allInOne == true


    - name: Add tag to (allInOne)
      local_action: ec2_tag
                         resource={{ item.id }}
                         region={{ region }}
                         state=present
      with_items: ec2.instances
      args:
        tags:
          Name: webInstance
      when: allInOne == true

#      allInOne end

#      allInDifferenet started
    -
      local_action:
        count: "{{ count }}"
        group_id: "{{ my_security_group.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ imageID }}"
        wait: true
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        module: ec2
      name:  "Create a Instance (allInDiff)"
      register: ec2
      when: allInDiff == true

    - name: Add new instance to host group(allInDiff)
      add_host: hostname={{ item.public_ip }} groupname=webInstance
      with_items: ec2.instances
      when: allInDiff == true


    - name: Wait for SSH to come up (allInDiff)
      local_action: wait_for
                          host={{ item.public_ip }}
                          port=22
                          state=started
      with_items: ec2.instances
      when: allInDiff == true


    - name: Add tag to (allInDiff)
      local_action: ec2_tag
                         resource={{ item.id }}
                         region={{ region }}
                         state=present
      with_items: ec2.instances
      args:
        tags:
          Name: webInstance
      when: allInDiff == true


    -
      local_action:
        count: "{{ count }}"
        group_id: "{{ my_security_group.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ imageID }}"
        wait: true
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        module: ec2
      name: "Create a Instance"
      register: ec2
      when: allInDiff == true


    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=DBInstance
      with_items: ec2.instances
      when: allInDiff == true


    - name: Wait for SSH to come up
      local_action: wait_for
                          host={{ item.public_ip }}
                          port=22
                          state=started
      with_items: ec2.instances
      when: allInDiff == true


    - name: Add tag to Instance(s)
      local_action: ec2_tag
                         resource={{ item.id }}
                         region={{ region }}
                         state=present
      with_items: ec2.instances
      args:
        tags:
          Name: DBInstance
      when: allInDiff == true

    -
      local_action:
        count: "{{ count }}"
        group_id: "{{ my_security_group.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ imageID }}"
        wait: true
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        module: ec2
      name: "Create a Instance"
      register: ec2
      when: allInDiff == true


    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=NGINXInstance
      with_items: ec2.instances
      when: allInDiff == true


    - name: Wait for SSH to come up
      local_action: wait_for
                          host={{ item.public_ip }}
                          port=22
                          state=started
      with_items: ec2.instances
      when: allInDiff == true


    - name: Add tag to Instance(s)
      local_action: ec2_tag
                         resource={{ item.id }}
                         region={{ region }}
                         state=present
      with_items: ec2.instances
      args:
        tags:
          Name: NGINXInstance
      when: allInDiff == true


#      allInDifferent end
#      DB&&NGINXInstance started

    -
      local_action:
        count: "{{ count }}"
        group_id: "{{ my_security_group.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ imageID }}"
        wait: true
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        module: ec2
      name: "Create a Instance"
      register: ec2
      when: DBAndNGINX == true

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=webInstance
      with_items: ec2.instances
      when: DBAndNGINX == true


    - name: Wait for SSH to come up
      local_action: wait_for
                          host={{ item.public_ip }}
                          port=22
                          state=started
      with_items: ec2.instances
      when: DBAndNGINX == true


    - name: Add tag to Instance(s)
      local_action: ec2_tag
                         resource={{ item.id }}
                         region={{ region }}
                         state=present
      with_items: ec2.instances
      args:
        tags:
          Name: webInstance
      when: DBAndNGINX == true



    -
      local_action:
        count: "{{ count }}"
        group_id: "{{ my_security_group.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ imageID }}"
        wait: true
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        module: ec2
      name: "Create a Instance"
      register: ec2
      when: DBAndNGINX == true

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=DB&&NGINXInstance
      with_items: ec2.instances
      when: DBAndNGINX == true


    - name: Wait for SSH to come up
      local_action: wait_for
                              host={{ item.public_ip }}
                              port=22
                              state=started
      with_items: ec2.instances
      when: DBAndNGINX == true


    - name: Add tag to Instance(s)
      local_action: ec2_tag
                             resource={{ item.id }}
                             region={{ region }}
                             state=present
      with_items: ec2.instances
      args:
        tags:
          Name: DB&&NGINXInstance
      when: DBAndNGINX == true



#      DBAndNGINX end

#      web&&DBInstance started
    -
      local_action:
        count: "{{ count }}"
        group_id: "{{ my_security_group.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ imageID }}"
        wait: true
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        module: ec2
      name: "Create a Instance"
      register: ec2
      when: webAndDBInstance == true

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=web&&DBInstance
      with_items: ec2.instances
      when: webAndDBInstance == true

    - name: Wait for SSH to come up
      local_action: wait_for
                          host={{ item.public_ip }}
                          port=22
                          state=started
      with_items: ec2.instances
      when: webAndDBInstance == true


    - name: Add tag to Instance(s)
      local_action: ec2_tag
                         resource={{ item.id }}
                         region={{ region }}
                         state=present
      with_items: ec2.instances
      args:
        tags:
          Name: web&&DBInstance
      when: webAndDBInstance == true

    -
      local_action:
        count: "{{ count }}"
        group_id: "{{ my_security_group.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ imageID }}"
        wait: true
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        module: ec2
      name: "Create a Instance"
      register: ec2
      when: webAndDBInstance == true

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=NGINXInstance
      with_items: ec2.instances
      when: webAndDBInstance == true


    - name: Wait for SSH to come up
      local_action: wait_for
                              host={{ item.public_ip }}
                              port=22
                              state=started
      with_items: ec2.instances
      when: webAndDBInstance == true

    - name: Add tag to Instance(s)
      local_action: ec2_tag
                             resource={{ item.id }}
                             region={{ region }}
                             state=present
      with_items: ec2.instances
      args:
        tags:
          Name: NGINXInstance
      when: webAndDBInstance == true


#      webAndDBInstance end

#      webAndNGINXInstance started

    -
      local_action:
        count: "{{ count }}"
        group_id: "{{ my_security_group.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ imageID }}"
        wait: true
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        module: ec2
      name: "Create a web-NGINX Instance"
      register: ec2
      when: webAndNGINXInstance == true

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=web&&NGINXInstance
      with_items: ec2.instances
      when: webAndNGINXInstance == true


    - name: Wait for SSH to come up
      local_action: wait_for
                          host={{ item.public_ip }}
                          port=22
                          state=started
      with_items: ec2.instances
      when: webAndNGINXInstance == true


    - name: Add tag to Instance(s)
      local_action: ec2_tag
                         resource={{ item.id }}
                         region={{ region }}
                         state=present
      with_items: ec2.instances
      args:
        tags:
          Name: web&&DBInstance
      when: webAndNGINXInstance == true

    -
      local_action:
        count: "{{ count }}"
        group_id: "{{ my_security_group.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ imageID }}"
        wait: true
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        module: ec2
      name: "Create a DBInstance"
      register: ec2
      when: webAndNGINXInstance == true


    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=DBInstance
      with_items: ec2.instances
      when: webAndNGINXInstance == true


    - name: Wait for SSH to come up
      local_action: wait_for
                              host={{ item.public_ip }}
                              port=22
                              state=started
      with_items: ec2.instances
      when: webAndNGINXInstance == true


    - name: Add tag to Instance(s)
      local_action: ec2_tag
                             resource={{ item.id }}
                             region={{ region }}
                             state=present
      with_items: ec2.instances
      args:
        tags:
          Name: DBInstance
      when: webAndNGINXInstance == true



-
  hosts: webInstance
  name: "launched an EC2 Instance - allInOne "
  remote_user: ubuntu
  gather_facts: false
  sudo: false
  when: allInOne == true

  vars:
    ansible_ssh_private_key_file: "/home/ubuntu/stageNeols.pem"

  vars_files:

      - conf/group_vars/conf.yml
      - environments/{{ env }}/group_vars/route53.yml

  roles:
      - instanceToReady
      - ec2
      - database
      - startProject
      - nginx


-
  hosts: DBInstance
  name: "launched an EC2 Instance "
  remote_user: ubuntu
  gather_facts: false
  sudo: false
  when: webAndNGINXInstance == true

  vars:
    ansible_ssh_private_key_file: "/home/ubuntu/stageNeols.pem"

  roles:

      - instanceToReady
      - database

-
  hosts: webInstance
  name: "launched an EC2 Instance"
  remote_user: ubuntu
  gather_facts: false
  sudo: false
  when: webAndNGINXInstance == true

  vars:
    ansible_ssh_private_key_file: "/home/ubuntu/stageNeols.pem"
    isDev: true
    isStage: false
    isProd: false

  roles:
      - ec2

-
  hosts: NGINXInstance
  name: "launched an EC2 Instance"
  remote_user: ubuntu
  gather_facts: false
  sudo: false

  vars:
    ansible_ssh_private_key_file: "/home/ubuntu/stageNeols.pem"

  roles:
      - nginx



