- name: "Get public IP address for Database"
  command: curl http://169.254.169.254/latest/meta-data/public-ipv4
  register: DBInstanceIP

- name: "Set fact on localhost"
  set_fact:
    launched_DBInstanceIP: "{{ DBInstanceIP.stdout }}"

- name: "Copy fact to other servers"
  set_fact:
    launched_DBInstanceIP: "{{ launched_DBInstanceIP }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['all'] }}"
  when: item != "localhost"

- name: Add mongo ppa key
  sudo: yes
  apt_key: >
    keyserver=hkp://keyserver.ubuntu.com:80
    id=7F0CEB10
    state=present

- name: Add mongo sources list
  sudo: yes
  lineinfile: >
    line="deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse"
    dest=/etc/apt/sources.list.d/mongodb.list
    state=present
    create=yes

- name: Install mongo
  sudo: yes
  apt: name=mongodb-org state=latest update_cache=yes

- name: "Creates directory"
  file: path=/home/ubuntu/neoData state=directory

- name: "copy neo database file"
  become: true
  become_user: root
  unarchive: src=neo.tar.gz
            dest=/home/ubuntu/neoData

- name: "copy neoHome database file"
  become: true
  become_user: root
  unarchive: src=neoHome.tar.gz
            dest=/home/ubuntu/neoData

- name: "mongo restore neo database"
  command: "mongorestore --port 27017 --db neo /home/ubuntu/neoData/neo"

- name: "mongo restore neoHome database"
  command: "mongorestore --port 27017 --db neo /home/ubuntu/neoData/neoHome"


