- name: Add MongoDB depenencey
  sudo: yes 
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

- name: MongoDB | Add  repository 
  sudo: yes 
  shell:
    echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

- name: Update system
  sudo: yes 
  command: apt-get update

- name: MongoDB Installation 
  sudo: yes 
  command: apt-get --assume-yes install -y mongodb-org

- name: copy private file from template
  sudo: yes
  template: src=mongoFile
            dest=/etc/systemd/system/mongodb.service
            mode=0600

- name: mongodb start
  sudo: yes
  command: systemctl start mongodb

- name: mongodb enable
  sudo: yes
  command: systemctl enable mongodb

- name: GIT Installation
  sudo: yes
  apt: name=git state=present

- name: Creates directory
  file: path=/home/ubuntu/Project state=directory
  file: path=/home/ubuntu/Project/EC2Automation state=directory

- name: Clone EC2Automation
  git: repo=https://github.com/vigneshavm/EC2Automation.git
       dest=/home/ubuntu/Project/EC2Automation

- name: "mongo Extract "
  command: "tar -xzvf /home/ubuntu/Project/EC2Automation/roles/ec2/DBbackup/neo.tar.gz"

- name: "mongo restore data"
  command: "mongorestore --port 27017 --db neo /home/ubuntu/neo"


