

- name: "Add MongoDB depenencey"
  become: true
  become_user: root
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5


- name: "MongoDB | Add  repository"
  become: true
  become_user: root
  shell:
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list

- name: Update system
  become: true
  become_user: root
  command: apt-get update

- name: "MongoDB Installation"
  become: true
  become_user: root
  command: apt-get --assume-yes install -y mongodb-org

- name: "Mongo Service start"
  become: true
  become_user: root
  command: service mongod start


- name: "change mongo BindIP"
  become: true
  become_user: root
  template: src=mongoFile
            dest=/etc/mongod.conf

- name: "Restart mongo server"
  become: true
  become_user: root
  command: service mongod restart
